### ISSUE TITLE
ICONE

### ISSUE THREAD

**Issue by alesoft73** [r-renato/ha-card-weather-conditions#1]
Ciao, vedo che sei di Roma per cui vado di Italiano;
Sto usando la tua card, l'unico problema sono le icone.
Non riesco a farle visualizzare.
Grazie infinite!

![Cattura](https://user-images.githubusercontent.com/46445679/81203929-d0f26880-8fc8-11ea-9ec0-903dd4215cf2.JPG)

**Comment by r-renato** [comment]
Ehi ciao,
le icone dipendono dal tipo di provider meteo che usi.
Questa card supporta le icone per `climacell`, `darksky` e `openweathermap`. E' sufficiente che lo indichi nell configurazione attraverso il parametro `icons_model`.

In ogni caso se continui a non vederle posta la configurazione della scheda. Inoltre se metti il browser in modalità sviluppatore puoi vedere se la scheda sta andando in errore, nel qual caso copia qui l'errore così vedo se c'è qualcosa da correggere.

Ciao,
Renato

**Comment by woody4165** [comment]
Ciao 
Anche io non vedo le icone
Ho installato l'integrazione di Climacell e uso quella nella card

Questa la configurazione

```
          - type: custom:ha-card-weather-conditions
            name: "ClimaCell"
            language: it
            animation: true
            camera: camera.meteoit
            pollen:
              tree:
                entity: sensor.cc_pollen_tree
                min: 0
                max: 5
                low: 1
                high: 3
              weed:
                entity: sensor.cc_pollen_weed
                min: 0
                max: 5
                low: 1
                high: 3
              grass:
                entity: sensor.cc_pollen_grass
                min: 0
                max: 5
                low: 1
                high: 3
            air_quality:
              pm25: sensor.cc_pm25
              pm10: sensor.cc_pm10
              o3: sensor.cc_o3
              no2: sensor.cc_no2
              co: sensor.cc_co
            weather:
              icons_model: climacell
              current:
                sun: sun.sun
                current_conditions: sensor.cc_weather_condition
                humidity: sensor.cc_humidity_percentage
                pressure: sensor.cc_barometric_pressure
                temperature: sensor.cc_temperature
                visibility: sensor.cc_visibility
                wind_bearing: sensor.cc_wind_direction
                wind_speed: sensor.cc_wind_speed
                precipitation: sensor.cc_precipitation
                forecast: true
              forecast:
                meteogram: camera.cc_c2
                icons:
                  day_1: sensor.cc_weather_condition_0d
                  day_2: sensor.cc_weather_condition_1d
                  day_3: sensor.cc_weather_condition_2d
                  day_4: sensor.cc_weather_condition_3d
                  day_5: sensor.cc_weather_condition_4d
                temperature_high:
                  day_1: sensor.cc_max_temperature_0d
                  day_2: sensor.cc_max_temperature_1d
                  day_3: sensor.cc_max_temperature_2d
                  day_4: sensor.cc_max_temperature_3d
                  day_5: sensor.cc_max_temperature_4d
                temperature_low:
                  day_1: sensor.cc_min_temperature_0d
                  day_2: sensor.cc_min_temperature_1d
                  day_3: sensor.cc_min_temperature_2d
                  day_4: sensor.cc_min_temperature_3d
                  day_5: sensor.cc_min_temperature_4d
                precipitation_probability:
                  day_1: sensor.cc_precipitation_probability_0d
                  day_2: sensor.cc_precipitation_probability_1d
                  day_3: sensor.cc_precipitation_probability_2d
                  day_4: sensor.cc_precipitation_probability_3d
                  day_5: sensor.cc_precipitation_probability_4d
                precipitation_intensity:
                  day_1: sensor.cc_max_precipitation_0d
                  day_2: sensor.cc_max_precipitation_1d
                  day_3: sensor.cc_max_precipitation_2d
                  day_4: sensor.cc_max_precipitation_3d
                  day_5: sensor.cc_max_precipitation_4d

```          
e come lo vedo

![Schermata 2020-05-06 alle 19 38 28](https://user-images.githubusercontent.com/6501444/81209765-3a767500-8fd1-11ea-87ee-9bc8281fd680.png)


Possibile sia questo l'errore?

![Schermata 2020-05-06 alle 19 40 06](https://user-images.githubusercontent.com/6501444/81209943-701b5e00-8fd1-11ea-8a56-530dca92e135.png)

**Comment by mfabiani53** [comment]
Off topic: dove e come riuscite a mostrare il meteogram (ha bisogno di una configurazione a parte?) e la camera? Mi date qualche dritta?

**Comment by woody4165** [comment]
cerca nella configurazione di esempio per `camera.`

dovrai già avere delle entità `camera.` con le immagini che vuoi mostrare

per quel che mi riguarda, meteogram da https://meteograms.com  l'altra immagine da http://www.centrometeo.com

**Comment by mfabiani53** [comment]
Ok grazie, per la camera ho risolto, ma cosa dovrei mettere nel meteogram usando una di quelle che mi consigli?

**Comment by woody4165** [comment]
io sono andato sul sito meteograms.com, ho messo la mia località, tasto destro sull'immagine e poi ho creato la camera con quel link.

**Comment by mfabiani53** [comment]
Ecco, il mio problema è come creare la camera con il link? E' un sensore? Potresti darmi il codice?

**Comment by woody4165** [comment]
https://www.home-assistant.io/integrations/generic_ip_camera/

**Comment by mfabiani53** [comment]
Ok, grazie... Per le icone, neanche io le vedo....

**Comment by r-renato** [comment]
Ciao,
per la camera io ho questa configurazione:
```
camera:
  - platform: generic
    name: "Acquafredda 1"
    still_image_url: https://hddn00.liveincam.com/snaps/4G00623PAG1CD9B.jpg
```

Le icone potrebbero non vedersi per un bug. Ho rilasciato un aggiornamento per questo. Potete aggiornare il pugin e riprovare?

Grazie, ciao.
Renato

**Comment by woody4165** [comment]
Grazie Renato.

Appena sarà disponibile in HACS lo provo.

**Comment by woody4165** [comment]
Ho aggiornato alla versione b65ae3a ma ancora non le vedo.

**Comment by r-renato** [comment]
Puoi mettere il browser in modalità developer e riportare qui gli errori che trovi dopo aver fatto il refresh della pagina?
Dovresti trovare  `WEATHER-CONDITION-CARD  1.0.0` e poi una serie di altre righe con degli errori, riportamele tutte per favore.

**Comment by alesoft73** [comment]
Non da nessun errore.... ma non escono

![immagine](https://user-images.githubusercontent.com/46445679/81236930-9a374500-8ffe-11ea-920a-49c6b10d2bd8.png)


ma e' ancora cosi':

![immagine](https://user-images.githubusercontent.com/46445679/81236993-b935d700-8ffe-11ea-9757-de351a493763.png)

**Comment by mfabiani53** [comment]
Non riesco a visualizzare le fasi della luna ed il fire index. C'è un'apposita configurazione per questi due sensori? I sensori sono presenti.

**Comment by alesoft73** [comment]
> 
> 
> Non riesco a visualizzare le fasi della luna ed il fire index. C'è un'apposita configurazione per questi due sensori? I sensori sono presenti.
> A proposito delle icone ecco quello che leggo nella console:
> 
> ![Schermata 2020-05-07 alle 09 53 27](https://user-images.githubusercontent.com/37701688/81268903-d98a8380-9048-11ea-9f1f-f9d9d1960abd.png)

Se intendi  Meteoalarm, devi iscriverti per le Api.
Le icone hanno la directory errata da quanto ho visto nel component.
Per cui penso ci metterà una pezza ;)

**Comment by rob196** [comment]
Awesome integration & card, regarding the icons though
 - The icons folder is not created in the path (`\config\www\community\ha-card-weather-conditions`) - hence why it cannot find them
 - Only has ha-card-weather-conditions.js and ha-card-weather-conditions.js.gz files in the folder

NOTE: I used hacs to install

**Comment by alesoft73** [comment]
Ecco qui....
il component richiama questa url...
"class="icon" style="background: none, url('null/animated/cloudy-original.svg') no-repeat;
background-size: contain"

Il nulle ovviamente non fa funzionare



correggendo funziona , ho provato con una sola icona.. ;)

..."icon" style="background: none, url('https://oxxxxxxxxx/local/community/ha-card-weather-conditions/icons/animated/cloudy-original.svg') no-repeat; 
                    background-size: contain



![immagine](https://user-images.githubusercontent.com/46445679/81274375-7e5c8f00-9050-11ea-8432-9075aab8a850.png)

**Comment by rob196** [comment]
Looks to be the imageCheck methods - below are my assumptions to fix:
 - Line 41: `weather `should be `animated`
 - Line 48: `/icons` should be removed

https://github.com/r-renato/ha-card-weather-conditions/blob/b65ae3a08f35bfeecda7792c9b3cae1923ff93e3/src/ha-card-weather-conditions.ts#L41-L50

**Comment by alesoft73** [comment]
Ora e' perfetto.
Grazie!
Se ti interessa abbiamo una community in telegram.
HASSIOHELP

**Comment by r-renato** [comment]
> Looks to be the imageCheck methods - below are my assumptions to fix:
> 
>     * Line 41: `weather `should be `animated`
> 
>     * Line 48: `/icons` should be removed
> 
> 
> https://github.com/r-renato/ha-card-weather-conditions/blob/b65ae3a08f35bfeecda7792c9b3cae1923ff93e3/src/ha-card-weather-conditions.ts#L41-L50

Thanks @rob196, your analysis is correct. I have fixed the code and released a new version. Please check if working fine now.

Thanks for your support.
Renato

**Comment by r-renato** [comment]
> Non riesco a visualizzare le fasi della luna ed il fire index. C'è un'apposita configurazione per questi due sensori? I sensori sono presenti.

No, non ancora. Ci lavorerò appena posso.
Ciao,
Renato

**Comment by mfabiani53** [comment]
Ok grazie...

**Comment by rbron01** [comment]
Great Card!

Icons are working if you use climacell but not working for Darksky icons.

**Comment by r-renato** [comment]
Hi, can you tell me the icon names that not working?

**Comment by r-renato** [comment]
> Ora e' perfetto.
> Grazie!
> Se ti interessa abbiamo una community in telegram.
> HASSIOHELP

Si, è interessante, appena ho un attimo provo ad unirmi. Grazie.

**Comment by mfabiani53** [comment]
On my side climacell icons are working good, darksky icons show only three days icons and openweathermap not showing icons....

**Comment by r-renato** [comment]
the plugin installed by HACS are deployed in the physical path `<homeassistant root>/www/community/`. To access it, HACS provides the url shortcut /`hacsfiles/<card name>/`.
`WEATHER-CONDITION-CARD 1.0.1 uses the HACS path to retrieve icons` means that the icons contained in the card can be retrieved via the HACS url shortcut.
In the latest version of the card, the missing icons are written in the browser console. Check their name and put it here.

**Comment by mfabiani53** [comment]
Must i create a folder inside the HACS url or put them in the root folder?

**Comment by r-renato** [comment]
no, HACS installs both card and icons.

**Comment by mfabiani53** [comment]
Sorry, but maybe i misunderstood.... i don't see any icon inside the  card HACS folder

**Comment by mfabiani53** [comment]
> per quel che mi riguarda, meteogram da https://meteograms.com l'altra immagine da http://www.centrometeo.com

Ma la prima richiede un API a pagamento?

**Comment by r-renato** [comment]
> Sorry, but maybe i misunderstood.... i don't see any icon inside the card HACS folder

Le trovi qui: <homeassistant root>/www/community/ha-card-weather-conditions/icons

**Comment by mfabiani53** [comment]
Scusa, ma ho appena aggiornato la card e dentro c'è solo questo:

![Schermata 2020-05-07 alle 19 31 37](https://user-images.githubusercontent.com/37701688/81326036-78d76700-9099-11ea-9bbd-4575667a3419.png)

**Comment by mfabiani53** [comment]
Ok, ho trovato la directory icons (da samba sembra nascosta) e dentro c'è la icona cloudy.svg. Perchè la console mi dice not found?

**Comment by r-renato** [comment]
prova postare il log della console, così vediamo di che si tratta. ti consiglio prima di svuotare la cache del browser per sicurezza.

**Comment by mfabiani53** [comment]
![Schermata 2020-05-07 alle 19 44 16](https://user-images.githubusercontent.com/37701688/81327251-4595d780-909b-11ea-8d09-02fabb404d97.png)

Una domanda: i sensori relativi ad epa sono disattivati sulla card? Così come le fasi lunari ed i fire index?

**Comment by r-renato** [comment]
questo non è un errore, è un test che serve a capire dove sono le icone. non ti appaiono nella card?

i dati per la qualità dell'aria sono sotto `Air Quality` in particolare `epa_aqi` e `epa_health_concern`. se ci agganci un sensore ti appaiono nella card.

**Comment by mfabiani53** [comment]
I sensori li ho, ma nella card non appaiono.

sensor.climacell_epa_health_concern
sensor.climacell_epa_primary_pollutant

Per le icon tutto a posto.

**Comment by mfabiani53** [comment]
![Schermata 2020-05-07 alle 19 54 22](https://user-images.githubusercontent.com/37701688/81328088-9bb74a80-909c-11ea-9805-c2c50d175240.png)

**Comment by r-renato** [comment]
controlla se il sensore ha un valore o non è valorizzato, nel caso verifica sempre nella console se ci sono errori

**Comment by mfabiani53** [comment]
I sensori sono valorizzati e dopo un clear cache è comparso un solo sensore (sensor.climacell_epa_health_concern) mentre l'altro è sempre assente... la console non dice nulla.

**Comment by r-renato** [comment]
il sensore `epa_primary_pollutant` non c'è perchè non è gestito :D

**Comment by mfabiani53** [comment]
Ah, ecco.... risolto ! :-)

**Comment by mfabiani53** [comment]
Which meteogram do you use in the readme?

**Comment by r-renato** [comment]
I use `yr.no`

A sample link is the following:
`https://www.yr.no/place/Italy/Basilicata/Acquafredda/meteogram.png`

**Comment by mfabiani53** [comment]
Ok e crei una camera con quel link? Oppure come lo inserisci nella card?

**Comment by r-renato** [comment]
Si, corretto. Configuri una cam e la usi nella card.

```
camera:
  - platform: generic
    still_image_url: https://www.yr.no/place/Italy/Basilicata/Acquafredda/meteogram.png
    name: "Acquafredda Meteogram"
```
