### ISSUE TITLE
2023-09 Update Seems to have broken card - Unexpected token '<', "<!DOCTYPE "... is not valid JSON in UI

### ISSUE THREAD

**Issue by Trebacz** [r-renato/ha-card-weather-conditions#107]
After updating to HA 2023.09 - a working card in a vertical card gives this UI error.

`Unexpected token '<', "<!DOCTYPE "... is not valid JSON`

Not exactly sure why, but here is My card yaml.

> 
```
type: custom:ha-card-weather-conditions
name: Palisades
weather:
  icons_model: climacell
  current:
    sun: sun.sun
    moon_phase: sensor.cc_test_moon_phase
    temperature: sensor.outside_temperature
    humidity: sensor.outdoor_humidity
    pressure: sensor.air_pressure
    wind_bearing: sensor.wind_direction
    wind_speed: sensor.wind_speed
air_quality:
  epa_aqi: sensor.e_sycamore_drive_air_quality_index
  epa_health_concern: `sensor.purpleair_description`
```
>
