### ISSUE TITLE
Invalid Date on forecast

### ISSUE THREAD

**Issue by Remko76** [r-renato/ha-card-weather-conditions#116]
I have upgraded the card to the latest 2.0.1 version and after some work got it working again. I keep being stuck with one issue on the forecast: It keeps showing me "invalid date" and I do not understand it. This is my configuration:

```
type: custom:ha-card-weather-conditions
language: de
animation: true
pollen:
  min: 1
  max: 5
  entities:
    - name: Weed
      entity: sensor.cc_weed_pollen_index_mod
    - name: Grass
      entity: sensor.cc_grass_pollen_index_mod
    - name: Tree
      entity: sensor.cc_tree_pollen_index_mod
weather:
  name: Auweiler
  icons_model: defaulthass
  sun: sun.sun
  moonphase: sensor.moon
  present:
    condition: sensor.cc_current_conditions
    temperature: sensor.outdoor_temperature
    humidity: sensor.humidity
    pressure: sensor.absolute_pressure
    wind_bearing: sensor.wind_direction
    wind_speed: sensor.wind_speed
  daily_forecasts:
    condition:
      slot1: sensor.cc_weather_condition_0d
      slot2: sensor.cc_weather_condition_1d
      slot3: sensor.cc_weather_condition_2d
      slot4: sensor.cc_weather_condition_3d
    temperature_high:
      slot1: sensor.cc_temperature_maximum_0d
      slot2: sensor.cc_temperature_maximum_1d
      slot3: sensor.cc_temperature_maximum_2d
      slot4: sensor.cc_temperature_maximum_3d
    temperature_low:
      slot1: sensor.cc_temperature_minimum_0d
      slot2: sensor.cc_temperature_minimum_1d
      slot3: sensor.cc_temperature_minimum_2d
      slot4: sensor.cc_temperature_minimum_3d
    precipitation_probability:
      slot1: sensor.cc_precipitation_probability_0d
      slot2: sensor.cc_precipitation_probability_1d
      slot3: sensor.cc_precipitation_probability_2d
      slot4: sensor.cc_precipitation_probability_3d
```

When I delete the "temperature_high", "temperature_low" and "precipitation_probability" sections, it does not show the "invalid date", but nothing at all besides the forecast icons (which work fine).

The Dev Tools section shows me following values for the forecast section:
sensor.cc_weather_condition_0d: cloudy
sensor.cc_temperature_maximum_0d: 20.0
sensor.cc_temperature_minimum_0d: 9.1
sensor.cc_precipitation_probability_0d: 15

Any ideas what could be wrong?

![Image](https://github.com/user-attachments/assets/6fabacaa-713d-42bc-84f5-a1c1423854bf)
