### ISSUE TITLE
Moon Phase text not displaying

### ISSUE THREAD

**Issue by romquenin** [r-renato/ha-card-weather-conditions#13]
Hello, i have a little problem with the card not displaying the Moon Phase Text:

![Screenshot 2020-05-21 at 20 15 32](https://user-images.githubusercontent.com/34734431/82592064-9845b800-9ba0-11ea-8904-f5800f4743c3.png)

```
          - type: custom:ha-card-weather-conditions
            name: "Météo"
            language: fr
            animation: true
            camera: camera.weather
            weather:
              icons_model: climacell
              current:
                sun: sun.sun
                moon_phase: sensor.cc_test_moon_phase                
                current_conditions: sensor.cc_test_weather_condition
                humidity: sensor.cc_test_humidity_percentage
                pressure: sensor.cc_test_barometric_pressure
                temperature: sensor.cc_test_temperature
                visibility: sensor.cc_test_visibility
                wind_bearing: sensor.cc_test_wind_direction
                wind_speed: sensor.cc_test_wind_speed
                precipitation: sensor.cc_test_precipitation
                forecast: true

```
![Screenshot 2020-05-21 at 20 24 07](https://user-images.githubusercontent.com/34734431/82592344-0db18880-9ba1-11ea-907f-aaa137cd9bd1.png)

I hope you can solve this.

Thanks again for your great work.
