### ISSUE TITLE
Use Default Weather Forecast

### ISSUE THREAD

**Issue by omayhemo** [r-renato/ha-card-weather-conditions#19]
The instructions show only using weather forecasts that have individual sensors for each day.
Is it possible to use the default weather entity?

**Comment by r-renato** [comment]
You can solve this problem using a card template. For example:

```
# lovelace_gen
####################################################################################################
# Params:
#   sensor_prefix
####################################################################################################
                            {% macro climacell_sensor(prefix, suffix) -%}
                            sensor.{{ prefix }}_{{ suffix }}
                            {%- endmacro %}

                              type: custom:ha-card-weather-conditions
                              name: {{ name }}
                              language: {{ locale }}
                              animation: false
                              weather:
                                icons_model: climatecell
                                forecast:
                                  icons:
                                    day_1: {{ climacell_sensor( sensor_prefix, 'weather_condition_0d' ) }}
                                    day_2: {{ climacell_sensor( sensor_prefix, 'weather_condition_1d' ) }}
                                    day_3: {{ climacell_sensor( sensor_prefix, 'weather_condition_2d' ) }}
                                    day_4: {{ climacell_sensor( sensor_prefix, 'weather_condition_3d' ) }}
                                    day_5: {{ climacell_sensor( sensor_prefix, 'weather_condition_4d' ) }}
                                  temperature_high:
                                    day_1: {{ climacell_sensor( sensor_prefix, 'max_temperature_0d' ) }}
                                    day_2: {{ climacell_sensor( sensor_prefix, 'max_temperature_1d' ) }}
                                    day_3: {{ climacell_sensor( sensor_prefix, 'max_temperature_2d' ) }}
                                    day_4: {{ climacell_sensor( sensor_prefix, 'max_temperature_3d' ) }}
                                    day_5: {{ climacell_sensor( sensor_prefix, 'max_temperature_4d' ) }}
                                  temperature_low:
                                    day_1: {{ climacell_sensor( sensor_prefix, 'min_temperature_0d' ) }}
                                    day_2: {{ climacell_sensor( sensor_prefix, 'min_temperature_1d' ) }}
                                    day_3: {{ climacell_sensor( sensor_prefix, 'min_temperature_2d' ) }}
                                    day_4: {{ climacell_sensor( sensor_prefix, 'min_temperature_3d' ) }}
                                    day_5: {{ climacell_sensor( sensor_prefix, 'min_temperature_4d' ) }}
                                  precipitation_probability:
                                    day_1: {{ climacell_sensor( sensor_prefix, 'precipitation_probability_0d' ) }}
                                    day_2: {{ climacell_sensor( sensor_prefix, 'precipitation_probability_1d' ) }}
                                    day_3: {{ climacell_sensor( sensor_prefix, 'precipitation_probability_2d' ) }}
                                    day_4: {{ climacell_sensor( sensor_prefix, 'precipitation_probability_3d' ) }}
                                    day_5: {{ climacell_sensor( sensor_prefix, 'precipitation_probability_4d' ) }}
                                  precipitation_intensity:
                                    day_1: {{ climacell_sensor( sensor_prefix, 'max_precipitation_0d' ) }}
                                    day_2: {{ climacell_sensor( sensor_prefix, 'max_precipitation_1d' ) }}
                                    day_3: {{ climacell_sensor( sensor_prefix, 'max_precipitation_2d' ) }}
                                    day_4: {{ climacell_sensor( sensor_prefix, 'max_precipitation_3d' ) }}
                                    day_5: {{ climacell_sensor( sensor_prefix, 'max_precipitation_4d' ) }}
```

For the use of this model see the following example:

```
      - type: custom:layout-card
        layout: vertical
        max_width: 100%
        cards:
          - id:
            type: horizontal-stack
            cards:
              - !include
                - ./lovelace_cards/card_weather_conditions.yaml
                - sensor_prefix: cc_acquafredda
                  name: Acquafredda
                  locale: it
```

I hope I gave a valid answer.
Thanks, 
Renato
