### ISSUE TITLE
Custom card not showed in UI

### ISSUE THREAD

**Issue by mfabiani53** [r-renato/ha-card-weather-conditions#2]
I configured all the sensors and they appeared in the list of sensors, configured card following your example but no card is displayed in the frontend.

This is my configuration:
```
- platform: climacell
  api_key: !secret climacell_api
  name: Climacell
  latitude: !secret latitude_casa
  longitude: !secret longitude_casa
  monitored_conditions:
    realtime:
      - weather_condition
      - temperature
      - humidity
      - visibility
      - cloud_cover
      - precipitation
      - precipitation_type
      - pressure
      - wind_speed
      - wind_direction
      - wind_gust
      - moon_phase
      - sunset
      - sunrise
      - pm25
      - pm10
      - o3
      - co
      - pollen_tree
      - pollen_weed
      - pollen_grass
      - fire_index
    forecast:
      - weather_condition
      - temperature
      - precipitation
      - precipitation_probability
  scan_interval:
      # At least one of these must be specified:
    days: 0
    hours: 3
    minutes: 0
    seconds: 0
    milliseconds: 0
```
And this is how i configured card:

```
          - type: custom:ha-card-weather-conditions
            name: 'Climacell'
            language: it
            animation: true
#            camera: camera.climacell_c1
            pollen:
              tree:
                entity: sensor.climacell_pollen_tree
                min: 0
                max: 5
                low: 1
                high: 3
              weed:
                entity: sensor.climacell_pollen_weed
                min: 0
                max: 5
                low: 1
                high: 3
              grass:
                entity: sensor.climacell_pollen_grass
                min: 0
                max: 5
                low: 1
                high: 3
              fire_index:
                entity: sensor.climacell_fire_index
                min: 0
                max: 5
                low: 1
                high: 3
            air_quality:
              pm25: sensor.climacell_pm25
              pm10: sensor.climacell_pm10
              o3: sensor.climacell_o3
#              no2: sensor.climacell_no2
              co: sensor.climacell_co
              so2: sensor.climacell_so2
#              epa_aqi: sensor.climacell_epa_aqi
#              epa_health_concern: sensor.climacell_epa_health_concern
            weather:
              icons_model: climacell
              current:
                sun: sun.sun
                current_conditions: sensor.climacellweather_condition
                humidity: sensor.climacell_humidity_percentage
                pressure: sensor.climacell_barometric_pressure
                temperature: sensor.climacell_temperature
                visibility: sensor.climacell_visibility
                wind_bearing: sensor.climacell_wind_direction
                wind_speed: sensor.climacell_wind_speed
                precipitation: sensor.climacell_precipitation
                forecast: true
            forecast:
#              meteogram: camera.climacell_c2
              icons:
                day_1: sensor.climacell_weather_condition_0d
                day_2: sensor.climacell_weather_condition_1d
                day_3: sensor.climacell_weather_condition_2d
                day_4: sensor.climacell_weather_condition_3d
                day_5: sensor.climacell_weather_condition_4d
              temperature_high:
                day_1: sensor.climacell_max_temperature_0d
                day_2: sensor.climacell_max_temperature_1d
                day_3: sensor.climacell_max_temperature_2d
                day_4: sensor.climacell_max_temperature_3d
                day_5: sensor.climacell_max_temperature_4d
              temperature_low:
                day_1: sensor.climacell_min_temperature_0d
                day_2: sensor.climacell_min_temperature_1d
                day_3: sensor.climacell_min_temperature_2d
                day_4: sensor.climacell_min_temperature_3d
                day_5: sensor.climacell_min_temperature_4d
              precipitation_probability:
                day_1: sensor.climacell_precipitation_probability_0d
                day_2: sensor.climacell_precipitation_probability_1d
                day_3: sensor.climacell_precipitation_probability_2d
                day_4: sensor.climacell_precipitation_probability_3d
                day_5: sensor.climacell_precipitation_probability_4d
              precipitation_intensity:
                day_1: sensor.climacell_max_precipitation_0d
                day_2: sensor.climacell_max_precipitation_1d
                day_3: sensor.climacell_max_precipitation_2d
                day_4: sensor.climacell_max_precipitation_3d
                day_5: sensor.climacell_max_precipitation_4d
```
In the console i get this:

![Schermata 2020-05-06 alle 19 18 33](https://user-images.githubusercontent.com/37701688/81210030-93dea400-8fd1-11ea-987c-541f2c0ae71b.png)
