### ISSUE TITLE
Meteogram, camera?

### ISSUE THREAD

**Issue by bsrdjan** [r-renato/ha-card-weather-conditions#20]
What are meteogram and camera and how to get it working?

I can't find any camera device or entity in my HA and would like to follow the README example:

```yaml
  camera: camera.cc_test_c1
  weather:
    forecast:
      meteogram: camera.cc_test_c2
```
