### ISSUE TITLE
feature-request: individual icons for pollen 

### ISSUE THREAD

**Issue by rywr** [r-renato/ha-card-weather-conditions#26]
Hello and thanks for your work!

I would like to use other sensor data for pollen information.
The provider I use offers several entities for pollen data, but all sensors have the same icon.
So inside the pollen view I can not differentiate between the entries. 
Could it be possible to define a individual icon for each pollen entry like this?

```
pollen:
  grass:
    entity: sensor.dwd_pollen_101_today_graeser
    icon: 'mdi:barley' #individual icon
    high: 4
    low: 2
    max: 6
    min: 0
```

Thanks
Ronny

**Comment by rywr** [comment]
I found a workaround. 
Using the customizing definition I'm able to change the icon for the sensor I want to use for pollen data.

```
homeassistant: 
  customize:
    sensor.dwd_pollen_101_today_graeser:
      icon: mdi:barley
```

But if you decide the icon option for pollen data would be nice, please include it :-)
