### ISSUE TITLE
Sea conditions

### ISSUE THREAD

**Issue by mfabiani53** [r-renato/ha-card-weather-conditions#28]
Is it possible to have an example about how to set the sea and the alert conditions?
I cannot see any docs about those two conditions, only how to set them in a lovelace card.
I added this to the configuration of the climacell sensor:

```
- platform: climacell
  api_key: !secret climacell_api
  name: Climacell
  latitude: !secret latitude_casa
  longitude: !secret longitude_casa
  monitored_conditions:
    sea:
      - swell_direction
      - swell_height
      - swell_period
      - wind_direction
      - wind_speed
      - air_temperature
      - water_temperature
```
But i got error in setting the sensor....
