### ISSUE TITLE
Card fails with JSON error on work network

### ISSUE THREAD

**Issue by K-Money** [r-renato/ha-card-weather-conditions#31]
When viewing the lovelace frontend from within my work's network, the Climacell Weather card fails to load and gives this error:

`Unexpected token < in JSON at position 0`

I can view the card fine from the local network as well as outside of the local network. It's only when within the work network that this specific card breaks. I suspect that due to my work's IT policies, some kind of call/request made by the card is being blocked that isn't otherwise blocked out in the wild. Although I don't understand A) Why the card would make a call when all the data is already available in the sensors (the sensors all work fine) B) Why the card fails in this big red way rather than just not appearing or not showing the small error'd section (e.g. not showing a temp value).

Note: Screenshot was from a couple versions ago so the entity names might be slightly out of date but the problem persists through the current version.

On work network:
![ClimacellError](https://user-images.githubusercontent.com/5406336/87236508-7813c780-c39f-11ea-8834-b4c85fb640a5.JPG)

On local network or outside network:
![ClimacellNormal](https://user-images.githubusercontent.com/5406336/87236547-d476e700-c39f-11ea-9c7d-6d1e9d4f79ec.JPG)

**Comment by r-renato** [comment]
Hi, 
the first sensor is sensor.<name>_0d, see the example:

```
type: custom:ha-card-weather-conditions
  name: "cc_test"
  language: it
  animation: true
  weather:
    icons_model: climacell
    forecast:
      meteogram: camera.cc_test_c2
      icons:
        day_1: sensor.cc_test_weather_condition_0d
        day_2: sensor.cc_test_weather_condition_1d
        day_3: sensor.cc_test_weather_condition_2d
        day_4: sensor.cc_test_weather_condition_3d
        day_5: sensor.cc_test_weather_condition_4d
      temperature_high:
        day_1: sensor.cc_test_temperature_max_0d
        day_2: sensor.cc_test_temperature_max_1d
        day_3: sensor.cc_test_temperature_max_2d
        day_4: sensor.cc_test_temperature_max_3d
        day_5: sensor.cc_test_temperature_max_4d
      temperature_low:
        day_1: sensor.cc_test_temperature_min_0d
        day_2: sensor.cc_test_temperature_min_1d
        day_3: sensor.cc_test_temperature_min_2d
        day_4: sensor.cc_test_temperature_min_3d
        day_5: sensor.cc_test_temperature_min_4d
      precipitation_probability:
        day_1: sensor.cc_test_precipitation_probability_0d
        day_2: sensor.cc_test_precipitation_probability_1d
        day_3: sensor.cc_test_precipitation_probability_2d
        day_4: sensor.cc_test_precipitation_probability_3d
        day_5: sensor.cc_test_precipitation_probability_4d
      precipitation_intensity:
        day_1: sensor.cc_test_precipitation_max_0d
        day_2: sensor.cc_test_precipitation_max_1d
        day_3: sensor.cc_test_precipitation_max_2d
        day_4: sensor.cc_test_precipitation_max_3d
        day_5: sensor.cc_test_precipitation_max_4d
```

Thanks, bye
Renato

**Comment by K-Money** [comment]
> Hi,
> the first sensor is sensor._0d, see the example:
> 
> ```
> type: custom:ha-card-weather-conditions
>   name: "cc_test"
>   language: it
>   animation: true
>   weather:
>     icons_model: climacell
>     forecast:
>       meteogram: camera.cc_test_c2
>       icons:
>         day_1: sensor.cc_test_weather_condition_0d
>         day_2: sensor.cc_test_weather_condition_1d
>         day_3: sensor.cc_test_weather_condition_2d
>         day_4: sensor.cc_test_weather_condition_3d
>         day_5: sensor.cc_test_weather_condition_4d
>       temperature_high:
>         day_1: sensor.cc_test_temperature_max_0d
>         day_2: sensor.cc_test_temperature_max_1d
>         day_3: sensor.cc_test_temperature_max_2d
>         day_4: sensor.cc_test_temperature_max_3d
>         day_5: sensor.cc_test_temperature_max_4d
>       temperature_low:
>         day_1: sensor.cc_test_temperature_min_0d
>         day_2: sensor.cc_test_temperature_min_1d
>         day_3: sensor.cc_test_temperature_min_2d
>         day_4: sensor.cc_test_temperature_min_3d
>         day_5: sensor.cc_test_temperature_min_4d
>       precipitation_probability:
>         day_1: sensor.cc_test_precipitation_probability_0d
>         day_2: sensor.cc_test_precipitation_probability_1d
>         day_3: sensor.cc_test_precipitation_probability_2d
>         day_4: sensor.cc_test_precipitation_probability_3d
>         day_5: sensor.cc_test_precipitation_probability_4d
>       precipitation_intensity:
>         day_1: sensor.cc_test_precipitation_max_0d
>         day_2: sensor.cc_test_precipitation_max_1d
>         day_3: sensor.cc_test_precipitation_max_2d
>         day_4: sensor.cc_test_precipitation_max_3d
>         day_5: sensor.cc_test_precipitation_max_4d
> ```
> 
> Thanks, bye
> Renato

Aye, the screenshot was from a couple versions ago but I keep the yaml up to date from the docs. The problem exists with correct configuration. Here's an updated screenshot.
![ClimacellError2](https://user-images.githubusercontent.com/5406336/87828272-6c0d8700-c831-11ea-994f-c0277098c697.JPG)

**Comment by r-renato** [comment]
Hi, can you put here your card config?
Thanks,
Renato

**Comment by K-Money** [comment]
Here's the current card config:

```
alert:
  fire_risk:
    entity: sensor.cc_climacell_fire_index
    icon: 'mdi:campfire'
    max: 100
    min: 1
    show_if_ge: 50
animation: true
language: en
type: 'custom:ha-card-weather-conditions'
weather:
  current:
    current_conditions: sensor.cc_climacell_weather_condition
    forecast: true
    humidity: sensor.netatmo_unit_01_backyard_humidity
    sun: sun.sun
    temperature: sensor.netatmo_unit_01_backyard_temperature
    wind_bearing: sensor.cc_climacell_wind_direction
    wind_speed: sensor.cc_climacell_wind_speed
  forecast:
    icons:
      day_1: sensor.cc_climacell_weather_condition_0d
      day_2: sensor.cc_climacell_weather_condition_1d
      day_3: sensor.cc_climacell_weather_condition_2d
      day_4: sensor.cc_climacell_weather_condition_3d
      day_5: sensor.cc_climacell_weather_condition_4d
    precipitation_intensity:
      day_1: sensor.cc_climacell_precipitation_max_0d
      day_2: sensor.cc_climacell_precipitation_max_1d
      day_3: sensor.cc_climacell_precipitation_max_2d
      day_4: sensor.cc_climacell_precipitation_max_3d
      day_5: sensor.cc_climacell_precipitation_max_4d
    precipitation_probability:
      day_1: sensor.cc_climacell_precipitation_probability_0d
      day_2: sensor.cc_climacell_precipitation_probability_1d
      day_3: sensor.cc_climacell_precipitation_probability_2d
      day_4: sensor.cc_climacell_precipitation_probability_3d
      day_5: sensor.cc_climacell_precipitation_probability_4d
    temperature_high:
      day_1: sensor.cc_climacell_temperature_max_0d
      day_2: sensor.cc_climacell_temperature_max_1d
      day_3: sensor.cc_climacell_temperature_max_2d
      day_4: sensor.cc_climacell_temperature_max_3d
      day_5: sensor.cc_climacell_temperature_max_4d
    temperature_low:
      day_1: sensor.cc_climacell_temperature_min_0d
      day_2: sensor.cc_climacell_temperature_min_1d
      day_3: sensor.cc_climacell_temperature_min_2d
      day_4: sensor.cc_climacell_temperature_min_3d
      day_5: sensor.cc_climacell_temperature_min_4d
  icons_model: climacell
```

**Comment by r-renato** [comment]
Please, try this configuration.
Thanks,
Renato

```
              - type: 'custom:ha-card-weather-conditions'
                animation: true
                language: en
                alert:
                  fire_risk:
                    entity: sensor.cc_climacell_fire_index
                    icon: 'mdi:campfire'
                    max: 100
                    min: 1
                    show_if_ge: 50
                weather:
                  current:
                    current_conditions: sensor.cc_climacell_weather_condition
                    forecast: true
                    humidity: sensor.netatmo_unit_01_backyard_humidity
                    sun: sun.sun
                    temperature: sensor.netatmo_unit_01_backyard_temperature
                    wind_bearing: sensor.cc_climacell_wind_direction
                    wind_speed: sensor.cc_climacell_wind_speed
                  forecast:
                    icons:
                      day_1: sensor.cc_climacell_weather_condition_0d
                      day_2: sensor.cc_climacell_weather_condition_1d
                      day_3: sensor.cc_climacell_weather_condition_2d
                      day_4: sensor.cc_climacell_weather_condition_3d
                      day_5: sensor.cc_climacell_weather_condition_4d
                    precipitation_intensity:
                      day_1: sensor.cc_climacell_precipitation_max_0d
                      day_2: sensor.cc_climacell_precipitation_max_1d
                      day_3: sensor.cc_climacell_precipitation_max_2d
                      day_4: sensor.cc_climacell_precipitation_max_3d
                      day_5: sensor.cc_climacell_precipitation_max_4d
                    precipitation_probability:
                      day_1: sensor.cc_climacell_precipitation_probability_0d
                      day_2: sensor.cc_climacell_precipitation_probability_1d
                      day_3: sensor.cc_climacell_precipitation_probability_2d
                      day_4: sensor.cc_climacell_precipitation_probability_3d
                      day_5: sensor.cc_climacell_precipitation_probability_4d
                    temperature_high:
                      day_1: sensor.cc_climacell_temperature_max_0d
                      day_2: sensor.cc_climacell_temperature_max_1d
                      day_3: sensor.cc_climacell_temperature_max_2d
                      day_4: sensor.cc_climacell_temperature_max_3d
                      day_5: sensor.cc_climacell_temperature_max_4d
                    temperature_low:
                      day_1: sensor.cc_climacell_temperature_min_0d
                      day_2: sensor.cc_climacell_temperature_min_1d
                      day_3: sensor.cc_climacell_temperature_min_2d
                      day_4: sensor.cc_climacell_temperature_min_3d
                      day_5: sensor.cc_climacell_temperature_min_4d
                  icons_model: climacell
```
