### ISSUE TITLE
Index Mismatch between Integration & Card

### ISSUE THREAD

**Issue by emouawad** [r-renato/ha-card-weather-conditions#34]
Daily Forecast in integration generate 0 based index: 
sensor.cc_temperature_min_0d  ... sensor.cc_temperature_min_4d

![image](https://user-images.githubusercontent.com/6771272/87797964-15657480-c854-11ea-8abf-5860bccdbb7b.png)

While Lovelace Card is looking for index starting from 1
![image](https://user-images.githubusercontent.com/6771272/87798070-34fc9d00-c854-11ea-8e7e-e9ad99054ffa.png)

Therefore last day of forecast will be lost

![image](https://user-images.githubusercontent.com/6771272/87798287-7b51fc00-c854-11ea-842c-9e3f07060a98.png)

**Comment by r-renato** [comment]
Hi,
the first sensor must be sensor.cc_test_weather_condition_0d, see example:

```
  type: custom:ha-card-weather-conditions
  name: "cc_test"
  language: it
  animation: true
  weather:
    icons_model: climacell
    forecast:
      meteogram: camera.cc_test_c2
      icons:
        day_1: sensor.cc_test_weather_condition_0d
        day_2: sensor.cc_test_weather_condition_1d
        day_3: sensor.cc_test_weather_condition_2d
        day_4: sensor.cc_test_weather_condition_3d
        day_5: sensor.cc_test_weather_condition_4d
      temperature_high:
        day_1: sensor.cc_test_temperature_max_0d
        day_2: sensor.cc_test_temperature_max_1d
        day_3: sensor.cc_test_temperature_max_2d
        day_4: sensor.cc_test_temperature_max_3d
        day_5: sensor.cc_test_temperature_max_4d
      temperature_low:
        day_1: sensor.cc_test_temperature_min_0d
        day_2: sensor.cc_test_temperature_min_1d
        day_3: sensor.cc_test_temperature_min_2d
        day_4: sensor.cc_test_temperature_min_3d
        day_5: sensor.cc_test_temperature_min_4d
      precipitation_probability:
        day_1: sensor.cc_test_precipitation_probability_0d
        day_2: sensor.cc_test_precipitation_probability_1d
        day_3: sensor.cc_test_precipitation_probability_2d
        day_4: sensor.cc_test_precipitation_probability_3d
        day_5: sensor.cc_test_precipitation_probability_4d
      precipitation_intensity:
        day_1: sensor.cc_test_precipitation_max_0d
        day_2: sensor.cc_test_precipitation_max_1d
        day_3: sensor.cc_test_precipitation_max_2d
        day_4: sensor.cc_test_precipitation_max_3d
        day_5: sensor.cc_test_precipitation_max_4d
```

thanks, bye
Renato
