### ISSUE TITLE
Custom element doesn't exist: ha-card-weather-conditions.

### ISSUE THREAD

**Issue by olia-bn** [r-renato/ha-card-weather-conditions#37]
Version installed: 87890c0 (PS: consider tagging stable releases?)
Home Assistant 0.113.0
HACS: 1.2.2
Browser: Version 84.0.4147.89 (Official Build) (64-bit) (Up to date)

`/hacsfiles/ha-card-weather-conditions/ha-card-weather-conditions.js` added via Configuration > Lovelace > Resources
Checked via via DevTools Network card and the file is loading

Sample code:
```
pollen:
  grass:
    entity: sensor.cc_castle_pollen_grass
    high: 3
    low: 1
    max: 5
    min: 0
  tree:
    entity: sensor.cc_castle_pollen_tree
    high: 3
    low: 1
    max: 5
    min: 0
  weed:
    entity: sensor.cc_castle_pollen_weed
    high: 3
    low: 1
    max: 5
    min: 0
type: 'custom:ha-card-weather-conditions'
```
