### ISSUE TITLE
Meteogram

### ISSUE THREAD

**Issue by joaopequeno-git** [r-renato/ha-card-weather-conditions#52]
Hello @r-renato can you help?
How to integrate  meteogram imagem from link: https://www.yr.no/place/Portugal/Coimbra/Cernache/avansert_meteogram.png

??

**Comment by r-renato** [comment]
Hi, 
look at this example:

```
camera:
  - platform: generic
    still_image_url: https://www.yr.no/place/Portugal/Coimbra/Cernache/avansert_meteogram.png
    name: "Cernache"
```
Thank, bye.
Renato
