### ISSUE TITLE
component fails to show: cannot load svg 404 (Not Found)

### ISSUE THREAD

**Issue by fspralja** [r-renato/ha-card-weather-conditions#57]
Hi,

cannot get the card working, here the error I get in console:
```
GET http://192.168.51.123:8123/local/ha-card-weather-conditions/icons/static/cloudy.svg 404 (Not Found)
Image (async)
(anonymous) @ ha-card-weather-conditions.js:270
setTimeout (async)
(anonymous) @ ha-card-weather-conditions.js:270
Ct @ ha-card-weather-conditions.js:270
(anonymous) @ ha-card-weather-conditions.js:381
ha-card-weather-conditions.js:381  WEATHER-CONDITION-CARD  1.9.6 use HACS path to retrieve icons.
ha-card-weather-conditions.js:270 Icons issue. States: icons_model=climacell - isDay=true - condition: na.
:8123/lovelace-doma/default_view:1 GET http://192.168.51.123:8123/local/community/ha-card-weather-conditions/icons/animated/undefined.svg 404 (Not Found)
```

on network tab I see some resources are loaded from correct location:
http://192.168.51.123:8123/local/community/ha-card-weather-conditions/icons/static/cloudy.svg

also with pollen enabled on card nothig shows with following exception in console:
```
ha-card-weather-conditions.js:335 Uncaught (in promise) TypeError: Cannot read property 'attributes' of undefined
    at Ht (ha-card-weather-conditions.js:335)
    at ha-card-weather-conditions.js:395
    at HTMLElement._render (ha-card-weather-conditions.js:399)
    at HTMLElement.render (ha-card-weather-conditions.js:390)
    at HTMLElement.update (ha-card-weather-conditions.js:1)
    at HTMLElement.performUpdate (ha-card-weather-conditions.js:1)
    at HTMLElement._enqueueUpdate (ha-card-weather-conditions.js:1)
```

card configuration is pretty much the one from the full card example
any hints? ty

**Comment by cunderw** [comment]
Post your card config and sensors config. There is likely something wrong in them.

**Comment by r-renato** [comment]
Hi, the calls:
```
GET http://192.168.51.123:8123/local/ha-card-weather-conditions/icons/static/cloudy.svg
GET http://192.168.51.123:8123/local/community/ha-card-weather-conditions/icons/static/cloudy.svg
```
are used to detect the card location. Only one of them catch the exception, the other contains the right card path.
Try to put here your card configuration to have a support.

Thanks,
Renato

**Comment by fspralja** [comment]
hi, here the card, it should be one copied from tutorial with some custom sensor values

```
type: 'custom:ha-card-weather-conditions'
animation: true
air_quality:
  co: sensor.cc_co
  epa_aqi: sensor.cc_epa_aqi
  epa_health_concern: sensor.cc_epa_health_concern
  no2: sensor.cc_no2
  o3: sensor.cc_o3
  pm10: sensor.cc_pm10
  pm25: sensor.pm2_5_1
  so2: sensor.cc_so2
weather:
  current:
    current_conditions: sensor.cc_weather_condition
    feels_like: sensor.windchill
    forecast: true
    humidity: sensor.humidity
    precipitation: sensor.rain_rate
    pressure: sensor.absolute_pressure
    sun: sun.sun
    temperature: sensor.outdoor_temperature
    visibility: sensor.cc_visibility
    wind_bearing: sensor.wind_direction
    wind_speed: sensor.wind_speed
  forecast:
    icons:
      day_1: sensor.cc_weather_condition_0d
      day_2: sensor.cc_weather_condition_1d
      day_3: sensor.cc_weather_condition_2d
      day_4: sensor.cc_weather_condition_3d
      day_5: sensor.cc_weather_condition_4d
    precipitation_intensity:
      day_1: sensor.cc_max_precipitation_0d
      day_2: sensor.cc_max_precipitation_1d
      day_3: sensor.cc_max_precipitation_2d
      day_4: sensor.cc_max_precipitation_3d
      day_5: sensor.cc_max_precipitation_4d
    precipitation_probability:
      day_1: sensor.cc_precipitation_probability_0d
      day_2: sensor.cc_precipitation_probability_1d
      day_3: sensor.cc_precipitation_probability_2d
      day_4: sensor.cc_precipitation_probability_3d
      day_5: sensor.cc_precipitation_probability_4d
    temperature_high:
      day_1: sensor.cc_max_temperature_0d
      day_2: sensor.cc_max_temperature_1d
      day_3: sensor.cc_max_temperature_2d
      day_4: sensor.cc_max_temperature_3d
      day_5: sensor.cc_max_temperature_4d
    temperature_low:
      day_1: sensor.cc_min_temperature_0d
      day_2: sensor.cc_min_temperature_1d
      day_3: sensor.cc_min_temperature_2d
      day_4: sensor.cc_min_temperature_3d
      day_5: sensor.cc_min_temperature_4d
  icons_model: climacell
```

ty
