### ISSUE TITLE
Show only the icon

### ISSUE THREAD

**Issue by RenzoBeux** [r-renato/ha-card-weather-conditions#6]
Hi, i want to only show the icon, so i use this:
```
animation: true
language: es
name: Clima
type: 'custom:ha-card-weather-conditions'
weather:
  current:
    current_conditions: sensor.cc_weather_condition
```

But then it shows like this: 
![image](https://user-images.githubusercontent.com/47984043/81830768-e0b30500-9512-11ea-8c4b-5eec8fec2044.png)

Can this be fixed?
Thank you!
Pd: amazing card bro!
