### ISSUE TITLE
Icon Model too big

### ISSUE THREAD

**Issue by Stephan1908** [r-renato/ha-card-weather-conditions#77]
Hi,
is there a way, to make the icon smaller?

![grafik](https://user-images.githubusercontent.com/60405276/116137176-82efdc80-a6d3-11eb-9d99-89bbbf3b85c0.png)

```
type: 'custom:ha-card-weather-conditions'
name: ' '
language: de
animation: false
weather:
  icons_model: defaulthass
  current:
    sun: sun.sun
    moon_phase: sensor.moon
    current_conditions: sensor.openweathermap_condition
    temperature: sensor.0017dbe9922673_actual_temperature
    humidity: sensor.0017dbe9922673_humidity
    pressure: sensor.openweathermap_pressure
    wind_speed: sensor.0017dbe9922673_wind_speed
    precipitation: sensor.openweathermap_forecast_precipitation
```
Greetings
