### ISSUE TITLE
Moon phase text instead of icon

### ISSUE THREAD

**Issue by Ayrton31** [r-renato/ha-card-weather-conditions#80]
Hello,

When I tried to show a simple card with the code below

```
type: 'custom:ha-card-weather-conditions'
name: Météo
language: fr
animation: true
weather:
  icons_model: climacell
  current:
    moon_phase: sensor.cc_climacell_moon_phase_0d
    current_conditions: sensor.cc_climacell_weather_condition
```
I have this vision on lovelace 
![image](https://user-images.githubusercontent.com/73702716/118524308-4e08ff80-b73e-11eb-9521-7b80e2aaf6e5.png)

Is something wrong with my configuration ?
